---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: 2010-09-09
Description: AWS SaaS Boost Onboarding Service
Parameters:
  Environment:
    Description: Environment name
    Type: String
  SaaSBoostBucket:
    Description: SaaS Boost assets S3 bucket
    Type: String
  LambdaSourceFolder:
    Description: Folder for lambda source code to change on each deployment
    Type: String
  SaaSBoostUtilsLayer:
    Description: Utils Layer ARN
    Type: String
  ApiGatewayHelperLayer:
    Description: API Gateway Helper Layer ARN
    Type: String
  CloudFormationUtilsLayer:
    Description: CloudFormation Utils Layer ARN
    Type: String
  SaaSBoostEventBus:
    Description: SaaS Boost Eventbridge Bus
    Type: String
  ResourcesBucket:
    Description: S3 bucket containing tenant custom config files (zip archive)
    Type: String
Resources:
  OnboardingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub sb-${Environment}-onboarding
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: SaaS Boost
          Value: !Ref Environment
  OnboardingTenantConfigQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub sb-${Environment}-onboarding-tenant-config
      VisibilityTimeout: 90
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OnboardingTenantConfigDLQ.Arn
        maxReceiveCount: 10
      SqsManagedSseEnabled: true
  OnboardingTenantConfigDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub sb-${Environment}-onboarding-tenant-config-dlq
      SqsManagedSseEnabled: true
  OnboardingTenantConfigQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref OnboardingTenantConfigQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Resource: !GetAtt OnboardingTenantConfigQueue.Arn
            Action:
              - SQS:SendMessage
  OnboardingTenantConfigEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sb-${Environment}-onboarding-tenant-config
      Description: SaaS Boost onboarding tenant config resources bucket events
      EventPattern: !Sub |
        {
          "source": [
            "aws.s3"
          ],
          "detail-type": [
            "Object Created"
          ],
          "detail": {
            "reason": [
              "PutObject"
            ],
            "bucket": {
              "name": [
                "${ResourcesBucket}"
              ]
            },
            "object": {
              "key": [{
                "prefix": "00temp"
              }]
            }
          }
        }
      State: ENABLED
      Targets:
        - Arn: !GetAtt OnboardingTenantConfigQueue.Arn
          Id: !Sub sb-${Environment}-onboarding-tenant-config
  OnboardingServiceBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Onboarding Service base policy for CRUD operations
      Path: '/'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:PutLogEvents
            Resource:
              - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:CreateLogStream
            Resource:
              - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
          - Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
            Resource:
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OnboardingTable}
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${SaaSBoostBucket}
              - !Sub arn:${AWS::Partition}:s3:::${ResourcesBucket}
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${SaaSBoostBucket}/*
              - !Sub arn:${AWS::Partition}:s3:::${ResourcesBucket}/*
          - Effect: Allow
            Action:
              - events:PutEvents
            Resource:
              - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/${SaaSBoostEventBus}
#          - Effect: Allow
#            Action:
#              - events:DescribeRule
#              - events:DeleteRule
#              - events:PutRule
#              - events:PutTargets
#              - events:RemoveTargets
#            Resource:
#              - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/*
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ChangeMessageVisibility
            Resource:
              - !GetAtt OnboardingTenantConfigQueue.Arn
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt OnboardingTenantConfigDLQ.Arn
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/saas-boost/${Environment}/PRIVATE_API_APP_CLIENT*
#          - Effect: Allow
#            Action:
#              - ecr:ListImages
#              - ecr:CreateRepository
#              - ecr:DeleteRepository
#              - ecr:TagResource
#              - ecr:UntagResource
#              - ecr:ListTagsForResource
#            Resource:
#              - !Sub arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*
#          - Effect: Allow
#            Action:
#              - cloudfront:GetDistribution
#            Resource:
#              - !Sub arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/*
#          - Effect: Allow
#            Action:
#              - apigateway:GET
#            Resource:
#              - !Sub arn:${AWS::Partition}:apigateway:*::/restapis/*
#          - Effect: Allow
#            Action:
#              - lambda:AddPermission
#              - lambda:RemovePermission
#              - lambda:InvokeFunction
#              - lambda:GetFunction
#              - lambda:GetFunctionConfiguration
#            Resource:
#              - !Sub '{{resolve:ssm:/saas-boost/${Environment}/CLEAR_BUCKET_ARN}}'
  OnboardingServiceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sb-${Environment}-onboarding-svc-role-${AWS::Region}
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref OnboardingServiceBasePolicy
  OnboardingServiceGetAllLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-get-all
      RetentionInDays: 30
  OnboardingServiceGetAll:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-get-all
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::getOnboardings
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
          ONBOARDING_TABLE: !Ref OnboardingTable
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Onboarding"
  OnboardingServiceGetByIdLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-get-by-id
      RetentionInDays: 30
  OnboardingServiceGetById:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-get-by-id
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::getOnboarding
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
          ONBOARDING_TABLE: !Ref OnboardingTable
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Onboarding"
  OnboardingServiceInsertLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-insert
      RetentionInDays: 30
  OnboardingServiceInsert:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-insert
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::insertOnboarding
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
          ONBOARDING_TABLE: !Ref OnboardingTable
          SAAS_BOOST_BUCKET: !Ref SaaSBoostBucket
          SAAS_BOOST_EVENT_BUS: !Ref SaaSBoostEventBus
          RESOURCES_BUCKET: !Ref ResourcesBucket
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Onboarding"
  OnboardingServiceUpdateLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-update
      RetentionInDays: 30
  OnboardingServiceUpdate:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-update
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::updateOnboarding
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
          ONBOARDING_TABLE: !Ref OnboardingTable
          SAAS_BOOST_BUCKET: !Ref SaaSBoostBucket
          SAAS_BOOST_EVENT_BUS: !Ref SaaSBoostEventBus
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
  OnboardingServiceDeleteLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-delete
      RetentionInDays: 30
  OnboardingServiceDelete:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-delete
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::deleteOnboarding
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
          ONBOARDING_TABLE: !Ref OnboardingTable
          SAAS_BOOST_BUCKET: !Ref SaaSBoostBucket
          SAAS_BOOST_EVENT_BUS: !Ref SaaSBoostEventBus
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
  OnboardingServiceEventHandlerLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-events
      RetentionInDays: 30
  OnboardingServiceEventHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-events
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::handleOnboardingEvent
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
          SAAS_BOOST_ENV: !Ref Environment
          ONBOARDING_TABLE: !Ref OnboardingTable
          API_APP_CLIENT: !Sub /saas-boost/${Environment}/PRIVATE_API_APP_CLIENT
          SAAS_BOOST_BUCKET: !Ref SaaSBoostBucket
          SAAS_BOOST_EVENT_BUS: !Ref SaaSBoostEventBus
          RESOURCES_BUCKET: !Ref ResourcesBucket
          TENANT_CONFIG_DLQ: !Ref OnboardingTenantConfigDLQ
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
  OnboardingTenantConfigLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-onboarding-tenant-config-event
      RetentionInDays: 30
  OnboardingTenantConfig:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-onboarding-tenant-config-event
      Role: !GetAtt OnboardingServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 89 # Must be less than the VisibilityTimeout setting on the queue
      MemorySize: 512
      Handler: com.amazon.aws.partners.saasfactory.saasboost.OnboardingService::processTenantConfigQueue
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/OnboardingService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
          SAAS_BOOST_ENV: !Ref Environment
          ONBOARDING_TABLE: !Ref OnboardingTable
          API_APP_CLIENT: !Sub /saas-boost/${Environment}/PRIVATE_API_APP_CLIENT
          SAAS_BOOST_BUCKET: !Ref SaaSBoostBucket
          SAAS_BOOST_EVENT_BUS: !Ref SaaSBoostEventBus
          TENANT_CONFIG_DLQ: !Ref OnboardingTenantConfigDLQ
          RESOURCES_BUCKET: !Ref ResourcesBucket
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
  OnboardingTenantConfigEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 0
      Enabled: true
      EventSourceArn: !GetAtt OnboardingTenantConfigQueue.Arn
      FunctionName: !GetAtt OnboardingTenantConfig.Arn
      FunctionResponseTypes:
        - ReportBatchItemFailures
  # Onboarding events _consumed_ by the control plane onboarding service
  OnboardingServiceEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sb-${Environment}-onboarding-events
      Description: SaaS Boost onboarding events
      EventBusName: !Ref SaaSBoostEventBus
      EventPattern:
        {
          "source": [
            "saas-boost"
          ],
          "detail-type": [
            "Onboarding Validated",
            "Onboarding Provisioning",
            "Onboarding Provisioned",
            "Onboarding Deploying",
            "Onboarding Deployed",
            "Onboarding Failed",
            "Tenant Deleted",
            "Tenant Enabled",
            "Tenant Disabled"
          ]
        }
      State: ENABLED
      Targets:
        - Arn: !GetAtt OnboardingServiceEventHandler.Arn
          Id: !Sub sb-${Environment}-onboarding-events
  OnboardingServiceEventsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnboardingServiceEventHandler
      Principal: events.amazonaws.com
      SourceArn: !GetAtt OnboardingServiceEventRule.Arn
Outputs:
  OnboardingServiceGetAllArn:
    Description: Onboarding Service get all onboarding requests Lambda ARN
    Value: !GetAtt OnboardingServiceGetAll.Arn
  OnboardingServiceInsertArn:
    Description: Onboarding Service insert onboarding request Lambda ARN
    Value: !GetAtt OnboardingServiceInsert.Arn
  OnboardingServiceByIdArn:
    Description: Onboarding Service get onboarding request by id Lambda ARN
    Value: !GetAtt OnboardingServiceGetById.Arn
...
