---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: 2010-09-09
Description: AWS SaaS Boost Metrics Service
Parameters:
  Environment:
    Description: Environment name
    Type: String
  SaaSBoostBucket:
    Description: SaaS Boost assets S3 bucket
    Type: String
  LambdaSourceFolder:
    Description: Folder for lambda source code to change on each deployment
    Type: String
  SaaSBoostUtilsLayer:
    Description: Utils Layer ARN
    Type: String
  ApiGatewayHelperLayer:
    Description: API Gateway Helper Layer ARN
    Type: String
#  AccessLogs:
#    Description: ALB Access Logs Bucket
#    Type: String
  AthenaOutput:
    Description: Web S3 bucket
    Type: String
  SaaSBoostApi:
    Description: SaaS Boost Private API
    Type: String
  ApiStage:
    Description: The API Gateway REST API stage name for the SaaS Boost private API
    Type: String
Resources:
#  AccessLogsDatabase:
#    Type: AWS::Glue::Database
#    Properties:
#      CatalogId: !Ref AWS::AccountId
#      DatabaseInput:
#        Description: SaaS Boost Access Logs Database
#        Name: !Sub sb_${Environment}_alb_access_logs
#  AccessLogsTable:
#    Type: AWS::Glue::Table
#    Properties:
#      CatalogId: !Ref AWS::AccountId
#      DatabaseName: !Ref AccessLogsDatabase
#      TableInput:
#        Description: ALB Access Logs from Tenants
#        Name: !Sub sb_${Environment}_access_logs
#        Owner: saas-boost
#        TableType: EXTERNAL_TABLE
#        StorageDescriptor:
#          Columns:
#            - Name: type
#              Type: STRING
#            - Name: time
#              Type: STRING
#            - Name: elb
#              Type: STRING
#            - Name: client_ip
#              Type: STRING
#            - Name: client_port
#              Type: INT
#            - Name: target_ip
#              Type: STRING
#            - Name: target_port
#              Type: INT
#            - Name: request_processing_time
#              Type: DOUBLE
#            - Name: target_processing_time
#              Type: DOUBLE
#            - Name: response_processing_time
#              Type: DOUBLE
#            - Name: elb_status_code
#              Type: STRING
#            - Name: target_status_code
#              Type: STRING
#            - Name: received_bytes
#              Type: BIGINT
#            - Name: sent_bytes
#              Type: BIGINT
#            - Name: request_verb
#              Type: STRING
#            - Name: request_url
#              Type: STRING
#            - Name: request_proto
#              Type: STRING
#            - Name: user_agent
#              Type: STRING
#            - Name: ssl_cipher
#              Type: STRING
#            - Name: ssl_protocol
#              Type: STRING
#            - Name: target_group_arn
#              Type: STRING
#            - Name: trace_id
#              Type: STRING
#            - Name: domain_name
#              Type: STRING
#            - Name: chosen_cert_arn
#              Type: STRING
#            - Name: matched_rule_priority
#              Type: STRING
#            - Name: request_creation_time
#              Type: STRING
#            - Name: actions_executed
#              Type: STRING
#            - Name: redirect_url
#              Type: STRING
#            - Name: lambda_error_reason
#              Type: STRING
#            - Name: target_port_list
#              Type: STRING
#            - Name: target_status_code_list
#              Type: STRING
#            - Name: new_field
#              Type: STRING
#          Compressed: False
#          Location: !Sub s3://${AccessLogs}/access-logs/AWSLogs/${AWS::AccountId}/elasticloadbalancing/${AWS::Region}
#          InputFormat: org.apache.hadoop.mapred.TextInputFormat
#          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
#          SerdeInfo:
#            SerializationLibrary: org.apache.hadoop.hive.serde2.RegexSerDe
#            Parameters:
#              serialization.format: 1
#              input.regex: '([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*):([0-9]*) ([^ ]*)[:-]([0-9]*) ([-.0-9]*) ([-.0-9]*) ([-.0-9]*) (|[-0-9]*) (-|[-0-9]*) ([-0-9]*) ([-0-9]*) \"([^ ]*) ([^ ]*) (- |[^ ]*)\" \"([^\"]*)\" ([A-Z0-9-]+) ([A-Za-z0-9.-]*) ([^ ]*) \"([^\"]*)\" \"([^\"]*)\" \"([^\"]*)\" ([-.0-9]*) ([^ ]*) \"([^\"]*)\" \"([^\"]*)\" \"([^ ]*)\" \"([^\s]+)\" \"([^\s]+)\"(.*)'
  MetricServiceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sb-${Environment}-metrics-svc-role-${AWS::Region}
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub sb-${Environment}-metrics-svc-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
              - Effect: Allow
                Action:
                  - athena:ListDataCatalogs
                  - athena:ListWorkGroups
                  - cloudwatch:GetMetricData
                  - cloudwatch:ListMetrics
                  - application-autoscaling:DescribeScalableTargets
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${AthenaOutput}
#                  - !Sub arn:${AWS::Partition}:s3:::${AccessLogs}
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetObject
                  - s3:ListMultipartUploadParts
                  - s3:PutObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${AthenaOutput}/*
#                  - !Sub arn:${AWS::Partition}:s3:::${AccessLogs}/*
              - Effect: Allow
                Action:
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:GetPartitions
                Resource:
#                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:database/${AccessLogsDatabase}
#                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/${AccessLogsDatabase}/${AccessLogsTable}
                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:${AWS::Partition}:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary
              - Effect: Allow
                Action:
                  - athena:*
                Resource:
                  - !Sub arn:${AWS::Partition}:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/saas-boost/${Environment}/PRIVATE_API_APP_CLIENT*
  MetricsServicePublishRequestCountLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-metrics-pub-requests
      RetentionInDays: 30
  MetricsServicePublishRequestCount:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-metrics-pub-requests
      Role: !GetAtt MetricServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 900
      MemorySize: 384
      Handler: com.amazon.aws.partners.saasfactory.saasboost.MetricService::publishRequestCountMetrics
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/MetricsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
#          ATHENA_DATABASE: !Ref AccessLogsDatabase
          S3_ATHENA_BUCKET: !Ref AthenaOutput
          S3_ATHENA_OUTPUT_PATH: !Sub s3://${AthenaOutput}/query-results/
#          ACCESS_LOGS_TABLE: !Ref AccessLogsTable
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Metrics"
  MetricsServicePublishResponseTimeLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-metrics-pub-response
      RetentionInDays: 30
  MetricsServicePublishResponseTime:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-metrics-pub-response
      Role: !GetAtt MetricServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 900
      MemorySize: 384
      Handler: com.amazon.aws.partners.saasfactory.saasboost.MetricService::publishResponseTimeMetrics
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/MetricsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
#          ATHENA_DATABASE: !Ref AccessLogsDatabase
          S3_ATHENA_BUCKET: !Ref AthenaOutput
          S3_ATHENA_OUTPUT_PATH: !Sub s3://${AthenaOutput}/query-results/
#          ACCESS_LOGS_TABLE: !Ref AccessLogsTable
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Metrics"
  MetricsServiceAddAthenaPartitionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-metrics-add-partition
      RetentionInDays: 30
  MetricsServiceAddAthenaPartition:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-metrics-add-partition
      Role: !GetAtt MetricServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 900
      MemorySize: 384
      Handler: com.amazon.aws.partners.saasfactory.saasboost.MetricService::addAthenaPartition
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/MetricsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
#          ATHENA_DATABASE: !Ref AccessLogsDatabase
          S3_ATHENA_BUCKET: !Ref AthenaOutput
          S3_ATHENA_OUTPUT_PATH: !Sub s3://${AthenaOutput}/query-results/
#          ACCESS_LOGS_TABLE: !Ref AccessLogsTable
#          ACCESS_LOGS_PATH: !Sub s3://${AccessLogs}/access-logs/AWSLogs/${AWS::AccountId}/elasticloadbalancing/${AWS::Region}
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Metrics"
  MetricServiceQueryLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-metrics-query
      RetentionInDays: 30
  MetricServiceQuery:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-metrics-query
      Role: !GetAtt MetricServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 1024
      Handler: com.amazon.aws.partners.saasfactory.saasboost.MetricService::queryMetrics
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/MetricsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
#          ATHENA_DATABASE: !Ref AccessLogsDatabase
          S3_ATHENA_BUCKET: !Ref AthenaOutput
          S3_ATHENA_OUTPUT_PATH: !Sub s3://${AthenaOutput}/query-results/
#          ACCESS_LOGS_TABLE: !Ref AccessLogsTable
          API_APP_CLIENT: !Sub /saas-boost/${Environment}/PRIVATE_API_APP_CLIENT
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Metrics"
  MetricsServiceGetDatasetsLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-metrics-datasets
      RetentionInDays: 30
  MetricsServiceGetDatasets:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-metrics-datasets
      Role: !GetAtt MetricServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 900
      MemorySize: 384
      Handler: com.amazon.aws.partners.saasfactory.saasboost.MetricService::getAccessMetricsSignedUrls
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/MetricsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
#          ATHENA_DATABASE: !Ref AccessLogsDatabase
          S3_ATHENA_BUCKET: !Ref AthenaOutput
          S3_ATHENA_OUTPUT_PATH: !Sub s3://${AthenaOutput}/query-results/
#          ACCESS_LOGS_TABLE: !Ref AccessLogsTable
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Metrics"
  MetricsServiceQueryAccessLogLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-metrics-access-log-query
      RetentionInDays: 30
  MetricsServiceQueryAccessLog:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-metrics-access-log-query
      Role: !GetAtt MetricServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 1024
      Handler: com.amazon.aws.partners.saasfactory.saasboost.MetricService::queryAccessLogs
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/MetricsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
        - !Ref ApiGatewayHelperLayer
      Environment:
        Variables:
#          ATHENA_DATABASE: !Ref AccessLogsDatabase
          S3_ATHENA_BUCKET: !Ref AthenaOutput
          S3_ATHENA_OUTPUT_PATH: !Sub s3://${AthenaOutput}/query-results/
#          ACCESS_LOGS_TABLE: !Ref AccessLogsTable
          API_APP_CLIENT: !Sub /saas-boost/${Environment}/PRIVATE_API_APP_CLIENT
      Tags:
        - Key: "Application"
          Value: "SaaSBoost"
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "BoostService"
          Value: "Metrics"
  PublishRequestCountEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sb-${Environment}-metrics-count
      Description: A scheduled task to publish access log metrics to s3 web bucket
      # Run this every 30 minutes
      ScheduleExpression: "cron(0/30 * * * ? *)"
      State: DISABLED
      Targets:
        - Arn: !GetAtt MetricsServicePublishRequestCount.Arn
          Id: MetricsServicePublishRequestCount
  PublishResponseTimeMetricsEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sb-${Environment}-metrics-latency
      Description: A scheduled task to publish access log metrics to s3 web bucket
      # Run this every 30 minutes
      ScheduleExpression: "cron(0/30 * * * ? *)"
      State: DISABLED
      Targets:
        - Arn: !GetAtt MetricsServicePublishResponseTime.Arn
          Id: MetricsServicePublishResponseTime
  AddAthenaPartitionEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub sb-${Environment}-metrics-athena-partition
      Description: A scheduled task to add partition for access logs daily
      # Run at 00:15 every day
      ScheduleExpression: "cron(15 0 * * ? *)"
      State: DISABLED
      Targets:
        - Arn: !GetAtt MetricsServiceAddAthenaPartition.Arn
          Id: MetricsServiceAddAthenaPartition
  MetricsServicePublishRequestCountPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MetricsServicePublishRequestCount.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PublishRequestCountEvent.Arn
  MetricsServicePublishResponseTimePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MetricsServicePublishResponseTime.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PublishResponseTimeMetricsEvent.Arn
  MetricsServiceAddAthenaPartitionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MetricsServiceAddAthenaPartition.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AddAthenaPartitionEvent.Arn
Outputs:
#  AccessLogsDatabase:
#    Description: Athena Database for ALB Access Logs
#    Value: !Ref AccessLogsDatabase
#  AccessLogsTable:
#    Description: Athena Access Logs Table
#    Value: !Ref AccessLogsTable
  QueryArn:
    Description: Metrics Service query Lambda ARN
    Value: !GetAtt MetricServiceQuery.Arn
  DatasetsArn:
    Description: Metrics Service datasets Lambda ARN
    Value: !GetAtt MetricsServiceGetDatasets.Arn
  AlbQueryArn:
    Description: Metrics Service ALB metric query Lambda ARN
    Value: !GetAtt MetricsServiceQueryAccessLog.Arn
...