---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: 2010-09-09
Description: AWS SaaS Boost Settings Service
Parameters:
  Environment:
    Description: Environment name
    Type: String
  SaaSBoostBucket:
    Description: SaaS Boost assets S3 bucket
    Type: String
  LambdaSourceFolder:
    Description: Folder for lambda source code to change on each deployment
    Type: String
  SaaSBoostUtilsLayer:
    Description: Utils Layer ARN
    Type: String
Resources:
  SettingsServiceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sb-${Environment}-settings-svc-role-${AWS::Region}
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub sb-${Environment}-settings-svc-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                  - ssm:GetParametersByPath
                  - ssm:DeleteParameter
                  - ssm:DeleteParameters
                Resource:
                  - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
  SettingsServiceGetAllLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-settings-get-all
      RetentionInDays: 30
  SettingsServiceGetAll:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-settings-get-all
      Role: !GetAtt SettingsServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 2112 # AWS Lambda Power Tuning balanced strategy
      Handler: com.amazon.aws.partners.saasfactory.saasboost.SettingsService::getSettings
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/SettingsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
          SAAS_BOOST_ENV: !Ref Environment
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
        - Key: BoostService
          Value: Settings
  SettingsServiceGetByIdLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-settings-get-by-id
      RetentionInDays: 30
  SettingsServiceGetById:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-settings-get-by-id
      Role: !GetAtt SettingsServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 2112 # AWS Lambda Power Tuning balanced strategy
      Handler: com.amazon.aws.partners.saasfactory.saasboost.SettingsService::getSetting
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/SettingsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
          SAAS_BOOST_ENV: !Ref Environment
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
        - Key: BoostService
          Value: Settings
  SettingsServiceGetSecretLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-settings-get-secret
      RetentionInDays: 30
  SettingsServiceGetSecret:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-settings-get-secret
      Role: !GetAtt SettingsServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 2112 # AWS Lambda Power Tuning balanced strategy
      Handler: com.amazon.aws.partners.saasfactory.saasboost.SettingsService::getSecret
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/SettingsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
          SAAS_BOOST_ENV: !Ref Environment
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
        - Key: BoostService
          Value: Settings
  SettingsServiceUpdateLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sb-${Environment}-settings-update
      RetentionInDays: 30
  SettingsServiceUpdate:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub sb-${Environment}-settings-update
      Role: !GetAtt SettingsServiceExecutionRole.Arn
      Runtime: java17
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 3072 # AWS Lambda Power Tuning balanced strategy
      Handler: com.amazon.aws.partners.saasfactory.saasboost.SettingsService::updateSetting
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub ${LambdaSourceFolder}/SettingsService-lambda.zip
      Layers:
        - !Ref SaaSBoostUtilsLayer
      Environment:
        Variables:
          SAAS_BOOST_ENV: !Ref Environment
      Tags:
        - Key: Application
          Value: SaaSBoost
        - Key: Environment
          Value: !Ref Environment
        - Key: BoostService
          Value: Settings
Outputs:
  SettingsServiceGetAllArn:
    Description: Settings Service get all settings Lambda ARN
    Value: !GetAtt SettingsServiceGetAll.Arn
  SettingsServiceByIdArn:
    Description: Settings Service get setting Lambda ARN
    Value: !GetAtt SettingsServiceGetById.Arn
  SettingsServiceGetSecretArn:
    Description: Settings Service get decrypted secret setting Lambda ARN
    Value: !GetAtt SettingsServiceGetSecret.Arn
  SettingsServiceUpdateArn:
    Description: Settings Service update setting Lambda ARN
    Value: !GetAtt SettingsServiceUpdate.Arn
...
