---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SaaS Boost Tenant Onboarding FSx for Windows File Server Extension
Parameters:
  Environment:
    Description: Environment (test, uat, prod, etc.)
    Type: String
  TenantId:
    Description: The GUID for the tenant
    Type: String
  SaaSBoostBucket:
    Description: SaaS Boost assets S3 bucket
    Type: String
  ServiceResourceName:
    Description: CloudFormation friendly version of the service name
    Type: String
  VPC:
    Description: VPC id for this tenant
    Type: AWS::EC2::VPC::Id
  PrivateSubnetA:
    Description: Choose the Id of the private subnet 1 in Availability Zone 1 (e.g., subnet-a0246dcd).
    Type: AWS::EC2::Subnet::Id
  PrivateSubnetB:
    Description: Choose the Id of the private subnet 2 in Availability Zone 2 (e.g., subnet-a0246dcd).
    Type: AWS::EC2::Subnet::Id
  ECSSecurityGroup:
    Description: Source security group of ECS instances
    Type: AWS::EC2::SecurityGroup::Id
  ActiveDirectoryId:
    Description: Id of the AWS Managed Microsoft AD. If you are using self-managed Active Directory, leave this blank.
    Type: String
  FSxEncryptionKey:
    AllowedValues:
      - 'Default'
      - 'GenerateKey'
      - 'UseKey'
    Description: Use the default AWS Key Management Service (AWS KMS) key for Amazon FSx, choose GenerateKey to create a key,
      or choose UseKey to use an existing key for encryption at rest on the Amazon FSx for Windows file system.
    Default: 'Default'
    Type: String
  FSxExistingKeyID:
    Description: If you chose the option to use an existing key, you must specify the KMS Key ID you want to use.
    Default: ''
    Type: String
  StorageCapacity:
    Default: 32
    Description: Specify the storage capacity of the file system being created, in gibibytes.
      Valid values are 32 GiB - 65,536 GiB.
    Type: Number
  ThroughputCapacity:
    Default: 8
    Description: Specify the throughput of the Amazon FSx file system. Valid values are 8 - 2048.
    Type: Number
  BackupRetention:
    Description: Number of days to retain automatic backups.
      Setting this to 0 disables the creation of automatic backups. The maximum retention period
      for backups is 35 days.
    Default: 7
    Type: Number
  DailyBackupTime:
    Description: Preferred time to take daily automatic backups, formatted HH:MM in the UTC time zone.
    Default: '01:00'
    Type: String
  WeeklyMaintenanceTime:
     Description: Specify the preferred start time to perform weekly maintenance, formatted d:HH:MM in the UTC time zone
     Default: '7:02:00'
     Type: String
Conditions:
  UseAWSDirectoryService: !Not [!Equals [!Ref ActiveDirectoryId, '']]
  HasKey: !Equals [!Ref FSxEncryptionKey, 'UseKey']
  CreateKey: !Equals [!Ref FSxEncryptionKey, 'GenerateKey']
  UseNonDefault: !Not [!Equals [!Ref FSxEncryptionKey, 'Default']]
Resources:
  FSxKMSKey:
    Condition: CreateKey
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub sb-${Environment}-fsx-key-${TenantId}-${ServiceResourceName}
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:CreateGrant
              - kms:ListGrants
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringEquals:
                kms:ViaService: !Sub fsx.${AWS::Region}.amazonaws.com
                kms:CallerAccount: !Ref 'AWS::AccountId'
      Tags:
        - Key: Name
          Value:
            Fn::Join: ['', ['sb-', !Ref Environment, '-fsx-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName]]
        - Key: Tenant
          Value: !Ref TenantId
  FSxKeyAlias:
    Condition: CreateKey
    Type: AWS::KMS::Alias
    Properties:
      AliasName:
        Fn::Join: ['', ['alias/sb-', !Ref Environment, '-fsx-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName]]
      TargetKeyId: !Ref FSxKMSKey
  FSxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: FSx File System Security Group
      GroupName:
        Fn::Join: ['', ['sb-', !Ref Environment, '-fsx-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName]]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 88
          ToPort: 88
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: udp
          FromPort: 88
          ToPort: 88
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: udp
          FromPort: 123
          ToPort: 123
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 135
          ToPort: 135
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: udp
          FromPort: 389
          ToPort: 389
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 389
          ToPort: 389
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: udp
          FromPort: 445
          ToPort: 445
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 445
          ToPort: 445
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: udp
          FromPort: 464
          ToPort: 464
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 464
          ToPort: 464
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 636
          ToPort: 636
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 3268
          ToPort: 3268
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 3269
          ToPort: 3269
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 5985
          ToPort: 5985
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 9389
          ToPort: 9389
          SourceSecurityGroupId: !Ref ECSSecurityGroup
        - IpProtocol: tcp
          FromPort: 49152
          ToPort: 65535
          SourceSecurityGroupId: !Ref ECSSecurityGroup
  WindowsFSx:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: WINDOWS
      KmsKeyId: !If
        - UseNonDefault
        - !If
          - HasKey
          - !Ref FSxExistingKeyID
          - !Ref FSxKMSKey
        - !Ref 'AWS::NoValue'
      StorageCapacity: !Ref StorageCapacity
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      SecurityGroupIds:
        - !Ref FSxSecurityGroup
      Tags:
        - Key: Tenant
          Value: !Ref TenantId
      WindowsConfiguration:
        ActiveDirectoryId: !If [UseAWSDirectoryService, !Ref ActiveDirectoryId, !Ref 'AWS::NoValue']
        WeeklyMaintenanceStartTime: !Ref WeeklyMaintenanceTime
        DailyAutomaticBackupStartTime: !Ref DailyBackupTime
        AutomaticBackupRetentionDays: !Ref BackupRetention
        DeploymentType: MULTI_AZ_1
        PreferredSubnetId: !Ref PrivateSubnetA
        ThroughputCapacity: !Ref ThroughputCapacity
  FsxDnsNameRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join: ['', ['sb-', !Ref Environment, '-fsx-dns-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName, '-', !Ref AWS::Region]]
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName:
            Fn::Join: ['', ['sb-', !Ref Environment, '-fsx-dns-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName, '-', !Ref AWS::Region]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:CreateLogStream
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'
              - Effect: Allow
                Action:
                  - fsx:DescribeFileSystems
                Resource: '*'
  FsxDnsNameLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join: ['', ['/aws/lambda/sb-', !Ref Environment, '-fsx-dns-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName]]
      RetentionInDays: 30
  FsxDnsNameFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - FsxDnsNameLogs
    Properties:
      FunctionName:
        Fn::Join: ['', ['sb-', !Ref Environment, '-fsx-dns-tenant-', !Select [0, !Split ['-', !Ref TenantId]], '-', !Ref ServiceResourceName]]
      Role: !GetAtt FsxDnsNameRole.Arn
      Runtime: java11
      Timeout: 870
      MemorySize: 640
      # Has to be a VPC Lambda because we're talking to FSx
      VpcConfig:
        SecurityGroupIds:
          - !Ref FSxSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: com.amazon.aws.partners.saasfactory.saasboost.FsxDnsName
      Code:
        S3Bucket: !Ref SaaSBoostBucket
        S3Key: !Sub '{{resolve:ssm:/saas-boost/${Environment}/SAAS_BOOST_LAMBDAS_FOLDER}}/FsxDnsName-lambda.zip'
      Layers:
         - !Sub '{{resolve:ssm:/saas-boost/${Environment}/UTILS_LAYER}}'
         - !Sub '{{resolve:ssm:/saas-boost/${Environment}/CFN_UTILS_LAYER}}'
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1'
      Tags:
        - Key: Tenant
          Value: !Ref TenantId
  InvokeGetFsxDnsName:
    Type: Custom::CustomResource
    DependsOn:
      - FsxDnsNameLogs
    Properties:
      ServiceToken: !GetAtt FsxDnsNameFunction.Arn
      FsxFileSystemId: !Ref WindowsFSx
Outputs:
  FileSystemId:
    Description: File System ID for FSx for Windows File Server
    Value: !Ref WindowsFSx
  WindowsFSxDnsName:
    Value: !GetAtt InvokeGetFsxDnsName.DnsName
    Description: FSx for Windows File Server DNS Name
