version: 0.2
phases:
  pre_build:
    commands:
      - if [ "$AWS_DEFAULT_REGION" = "cn-northwest-1" ] || [ "$AWS_DEFAULT_REGION" = "cn-north-1" ]; then npm config set registry https://registry.npm.taobao.org; fi
      - aws s3 cp s3://$SOURCE_BUCKET/${SOURCE_BUCKET_PREFIX}client/api-docs/src.zip src.zip
      - unzip src.zip
      - aws s3 cp s3://$SOURCE_BUCKET/${SOURCE_BUCKET_PREFIX}client/api-docs/swagger.json ./resources/api-docs/swagger.json
  build:
    commands:
      - cd ./resources/api-docs
      - npm install
      - cd ../../
cache:
  paths:
    - $CODEBUILD_SRC_DIR/resources/api-docs/node_modules/**/*
